import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import Button from "../components/button/Button";
import { useEffect, useState } from "react";

export default function Home() {
  const [state, setState] = useState({ data: "" });

  useEffect(() => {
    getData();
    async function getData() {
      const response = await fetch("/api/data-for-react");
      const data = await response.json();
      setState(data);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/favicon.ico" />
      </Head>
      <Main>
        <div>
          <Headline>Tracker für Sexismus und Diskriminierung</Headline>
          <Container>
            <Headline2>Was ist passiert?</Headline2>
            <Text>Hier ist Platz, um deine Erlebnisse aufzuschreiben. </Text>
            <Link href="/incidents" passHref>
              <NavButton variant="contained">Schreib es auf</NavButton>
            </Link>
          </Container>
          <Container>
            <Headline2>Deine Erlebnisse</Headline2>
            <Text>
              Du hast die Möglichkeit deine Einträge zu speichern und später
              erneut auf sie zuzugreifen.
            </Text>
            <Link href="/incidents/incidentList" passHref>
              <NavButton variant="contained">Deine Einträge</NavButton>
            </Link>
          </Container>
          <Container>
            <Headline2>Hilfestellen und Beratungsangebote</Headline2>
            <Text>
              Du bist nicht allein! Wir haben dir eine Liste mit verschiedenen
              Hilfs- und Beratungsangeboten zusammengestellt. Hier findest du
              Angebote und Kontaktmöglichkeiten.
            </Text>
            <Link href="/resources" passHref>
              <NavButton variant="contained">Hilfsangebote</NavButton>
            </Link>
          </Container>
        </div>
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
  cursor: pointer;
`;

const Container = styled.div`
  text-align: center;
  padding: 10px;
  margin: 10px;
  border-radius: 15px 15px 15px 15px;
  box-shadow: 0px 10px 13px -7px #3d2443, 13px -4px 36px 3px rgba(0, 0, 0, 0.35);
  cursor: default;
`;

const Headline = styled.h1`
  text-align: center;
  padding: 10px;
  margin: 10px;
`;

const Headline2 = styled.h2`
  padding: 10px;
  margin: 10px;
`;

const Text = styled.p`
  text-align: center;
  padding: 10px;
  margin: 10px;
`;

const NavButton = styled(Button)`
  margin: auto;
  position: relative;
`;
