import Head from "next/head";
import styled from "styled-components";
import Button from "../components/button/Button";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Card from "../components/card/Card";

export default function Home() {
  const [state, setState] = useState({ data: "" });

  useEffect(() => {
    getData();
    async function getData() {
      const response = await fetch("/api/data-for-react");
      const data = await response.json();
      setState(data);
    }
  }, []);

  const router = useRouter();

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/favicon.ico" />
      </Head>
      <Main>
        <div>
          <Headline>Tracker für Sexismus und Diskriminierung</Headline>
          <HomeCard>
            <Headline2>Was ist passiert?</Headline2>
            <Text>Hier ist Platz, um deine Erlebnisse aufzuschreiben. </Text>
            <PagesButton
              type="button"
              onClick={() => router.push("/incidents")}
            >
              Schreib es auf
            </PagesButton>
          </HomeCard>
          <HomeCard>
            <Headline2>Deine Erlebnisse</Headline2>
            <Text>
              Du hast die Möglichkeit deine Einträge zu speichern und später
              erneut auf sie zuzugreifen.
            </Text>

            <PagesButton
              type="button"
              onClick={() => router.push("/incidents/incidentList")}
            >
              Deine Einträge
            </PagesButton>
          </HomeCard>
          <HomeCard>
            <Headline2>Hilfestellen und Beratungsangebote</Headline2>
            <Text>
              Du bist nicht allein! Wir haben dir eine Liste mit verschiedenen
              Hilfs- und Beratungsangeboten zusammengestellt. Hier findest du
              Angebote und Kontaktmöglichkeiten.
            </Text>

            <PagesButton
              type="button"
              onClick={() => router.push("/resources")}
            >
              Hilfestellen
            </PagesButton>
          </HomeCard>
        </div>
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
  cursor: pointer;
`;

const HomeCard = styled(Card)`
  text-align: center;
  padding: 10px;
`;

const Headline = styled.h1`
  text-align: center;
  padding: 10px;
  margin: 10px;
`;

const Headline2 = styled.h2`
  padding: 10px;
  margin: 10px;
`;

const Text = styled.p`
  text-align: center;
  padding: 10px;
  margin: 10px;
`;

const PagesButton = styled(Button)`
  margin: auto;
  position: relative;
`;
